apiVersion: apps/v1
kind: Deployment
metadata:
  name: mbinet
  namespace: mbinet-prod
spec:
  selector:
    matchLabels:
      app: mbinet
  replicas: 1
  template:
    metadata:
      labels:
        app: mbinet
    spec:
      containers:
        - name: mbinet
          image: registry.empatnusabangsa.com/empatnusabangsa/mbinet-fe:1
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: regcred
